eventsite/admin/urls.py
from django.conf.urls.defaults import *
from tasks import migrate_events, migrate_profiles, migrate_sources

urlpatterns = patterns('eventsite.admin.views',
      url(r'^$','index', name="admin-home"),
      url(r'^create/$','create_site', name="create-site"),
      url(r'^logo/$','logo', name="logo-upload"),
      url(r'^edit/$','edit_site', name="edit-site"),
      url(r'^users/$','manage_users', name="manage-users"),
      url(r'^configure-mailchimp', 'configure_mailchimp', name="configure-mailchimp"),
      url(r'^migrate/$','migrate',),
      url(r'^migrate-events/$',migrate_events,),
      url(r'^migrate-profiles/$',migrate_profiles,),
      url(r'^migrate-sources/$',migrate_sources,),
      

)

eventsite/urls.py
# Copyright 2008 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from django.conf.urls.defaults import *

urlpatterns = patterns('',
    url(r'^$','eventsite.views.front_page', name="front-page"),
    url(r'^jumpto/$','eventsite.views.jumpto', name="jumpto"),
    url(r'^ical/$','eventsite.views.ical', name="ical"),
    url(r'^events.json$','eventsite.views.make_json', name="json"),
    url(r'^thisweek.xml$','eventsite.views.this_week_rss', name="weekly_rss"),
    url(r'^week-of/(?P<datestring>[\x20-\x7E]+)/(?P<format>[\x20-\x7E]+)$','eventsite.views.week_of_index', name="week-of-with-format"),
    url(r'^week-of/(?P<datestring>[\x20-\x7E]+)$','eventsite.views.week_of_index', name="week-of"),
)

urls.py
# Copyright 2008 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from django.conf.urls.defaults import *

urlpatterns = patterns('',
    # Example:
    (r'^account/', include('account.urls')),
    url(r'^_ah/login_required', 'account.views.signin', name="account-signin"),
    (r'^events/', include('events.urls')),
    (r'^sources/', include('sources.urls')),
    (r'^subscriptions/', include('subscriptions.urls')),
    (r'^admin/', include('eventsite.admin.urls')),
    (r'^assets/', include('assets.urls')),
    (r'^links/', include('links.urls')),
    (r'', include('eventsite.urls')),
)

newsletter/models.py
from google.appengine.ext import db
from eventsite.models import Eventsite

class Edition(db.Model):
    published=db.DateTimeProperty()
    issue_num=db.IntegerProperty(required=True)
    subject=db.StringProperty(required=True)
    body_txt=db.TextProperty(required=True)
    body_html=db.TextProperty()
    status=db.StringProperty(required=True)
    publish_after=db.DateTimeProperty(required=True)
    site=db.ReferenceProperty(Eventsite, required=True)

account/forms.py
from django import forms
from django.forms.util import ErrorList
from django.template.defaultfilters import slugify

from google.appengine.api.users import get_current_user
from account.utility import profile_required, get_current_profile

from models import Profile
from eventsite import get_site

from html5.forms import URLInput, DateInput, TextInput, EmailInput



class ProfileForm(forms.Form):
    nickname = forms.CharField(max_length=255, help_text="What you want to be known as on the site")
    email=forms.EmailField(required=True, help_text="Where should we send email?", widget=EmailInput)
    subscribe = forms.BooleanField(required=False, help_text="Do you want to get the weekly events email?")
    link=forms.URLField(required=False, help_text="This can be the URL of your blog, twitter page, LinkedIn profile, homepage, or anything else.", 
                        widget=TextInput(attrs={'placeholder':'http://whatever'}))

    def clean(self):
        site=get_site()
        cleaned_data = self.cleaned_data
        nickname = cleaned_data.get("nickname")
        email = cleaned_data.get("email")
        profile=get_current_profile()
        existing_profile_with_slug=site.profile_set.filter('slug =', unicode(slugify(nickname))).get()
        existing_profile_with_email=site.profile_set.filter('email =', email).get()
        if (existing_profile_with_slug != None and existing_profile_with_slug.key() != profile.key()):
                msg = u"Someone else already took that nickname!"
                self._errors["nickname"] = ErrorList([msg])
                del cleaned_data['nickname']
        if (existing_profile_with_email != None and existing_profile_with_email.key() != profile.key()):
                msg = u"Someone has already registered with that email"
                self._errors["email"] = ErrorList([msg])
                del cleaned_data['email']
                
        return super(ProfileForm, self).clean()

eventsite/admin/forms.py
from django import forms
from django.forms.util import ErrorList
from django.template.defaultfilters import slugify
from eventsite import get_site
from eventsite.models import SitesMailchimp

from tz_helper import common_timezones_set

timezones=sorted(zip(common_timezones_set,common_timezones_set))

class SiteCreateForm(forms.Form):
    name = forms.CharField(max_length=255, required=True)
    timezone=forms.ChoiceField(choices=timezones)
    slug=forms.CharField(max_length=255, required=True)
    audience=forms.CharField(max_length=255, required=True)
    
class SiteDetailsForm(forms.Form):
    name = forms.CharField(max_length=255, required=True)
    timezone=forms.ChoiceField(choices=timezones)
    audience=forms.CharField(max_length=255, required=True)
    google_analytics_code=forms.CharField(max_length=255, required=False)
    google_site_verification=forms.CharField(max_length=255, required=False)
    twitter=forms.CharField(max_length=255, required=False)
    bsa_code=forms.CharField(max_length=255, required=False, widget=forms.Textarea)
    offline=forms.BooleanField(required=False)
    hostnames=forms.CharField(max_length=255, required=False)
    
    
    def clean_hostnames(self):
        cd=self.cleaned_data
        return [h.strip().lower() for h in cd['hostnames'].split(',')]



class LogoUploadForm(forms.Form):
    upload=forms.FileField(required=True)
    
class MailChimpApiKey(forms.Form):
    mailchimp_api_key = forms.CharField(max_length=255, required=True)
    
    def save(self):
        site=get_site()
        mc=SitesMailchimp(parent=site, apikey=self.cleaned_data['mailchimp_api_key'])
        mc.put()
        return mc
        
        


        
        

eventsite/admin/views.py
import logging,os
import namespace_registry
from django.shortcuts import render_to_response
from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext
from django.template.defaultfilters import slugify, striptags
from django.core.urlresolvers import reverse
from django.contrib import messages

from google.appengine.ext import blobstore
from google.appengine.ext import db
from google.appengine.api import images
from google.appengine.api.labs import taskqueue
from google.appengine.ext.db import Query
from google.appengine.api.images import get_serving_url

from account.utility import admin_required, profile_required
from forms import SiteDetailsForm, LogoUploadForm, SiteCreateForm, MailChimpApiKey
from eventsite import get_site, site_required, models, site_cache
from blob_helper import get_uploads
from django import forms
from google.appengine.api.namespace_manager import set_namespace
import namespace_registry



import pychimp, logging

@admin_required
def create_site(request):
    hostname=request.get_host()
    site=get_site()
    if site:return HttpResponseRedirect(reverse('admin-home'))
    form=SiteCreateForm()
    if request.method == 'POST':
        form=SiteCreateForm(request.POST)
        if form.is_valid():
            new_site=models.Eventsite(name=form.cleaned_data['name'].strip(),
                                    timezone= form.cleaned_data['timezone'].strip(),
                                    audience=form.cleaned_data['audience'].strip(),
                                    hostnames=[hostname,],
                                    key_name=hostname,
                                    slug=form.cleaned_data['slug'])
            new_site.put()
            return HttpResponseRedirect(reverse('admin-home'))
    return render_to_response('eventsite/admin.html', locals(), context_instance=RequestContext(request))
        
            
  
@admin_required
def index(request):
      site=get_site()
      if not site: 
          return HttpResponseRedirect(reverse('create-site'))
      else:
          return HttpResponseRedirect(reverse('edit-site'))
  

@admin_required
def edit_site(request):
    site=get_site()
    if not site: return HttpResponseRedirect(reverse('create-site'))

    if request.method == 'POST': # If the form has been submitted...
        form = SiteDetailsForm(request.POST) # A form bound to the POST data
        if form.is_valid(): # All validation rules pass
            site.name=form.cleaned_data['name'].strip()
            site.timezone= form.cleaned_data['timezone'].strip()
            site.audience=form.cleaned_data['audience'].strip()
            site.hostnames=form.cleaned_data['hostnames']
            site.google_site_verification=form.cleaned_data['google_site_verification'].strip()
            site.google_analytics_code=form.cleaned_data['google_analytics_code'].strip()
            site.twitter=form.cleaned_data['twitter'] or None
            site.bsa_code=form.cleaned_data['bsa_code'] or None
            site.offline=form.cleaned_data['offline'] or None
            site.put()
            site.expire_assets()

            
    else:
        site=get_site()
        if site:
            site_details={'name':site.name, 'timezone':site.timezone, 'slug':site.slug,
            'audience': site.audience, 'hostnames':",".join(site.hostnames),
            'google_analytics_code':site.google_analytics_code,
            'google_site_verification':site.google_site_verification,
            'twitter':site.twitter,
            }
            form=SiteDetailsForm(site_details)
        else:    
            form = SiteDetailsForm() # An unbound form

   
    return render_to_response('eventsite/admin.html', locals(), context_instance=RequestContext(request))
    
     


@admin_required
def configure_mailchimp(request):
    site=get_site()
    mc=models.SitesMailchimp.all().ancestor(site).get()
    if not mc:
        if request.method == 'POST':
            form=MailChimpApiKey(request.POST)
            if form.is_valid():
                form.save()
                return HttpResponseRedirect(reverse('configure-mailchimp'))
        else:
            form = MailChimpApiKey()    
        
        return render_to_response('admin/mailchimp_apikey.html', locals(), context_instance=RequestContext(request))

    else:
        chimp=pychimp.PyChimp(mc.apikey)
        lists=chimp.lists()
        list_choices=[(l['id']+'!@!'+l['name'], l['name']) for l in lists]
        
        class MailChimpListForm(forms.Form):
            mailchimp_list=forms.ChoiceField(choices=list_choices)
            
            def save(self):
                mc.listid, mc.listname=self.cleaned_data['mailchimp_list'].split('!@!')
                mc.put()
        
        if request.method=='POST':
            form=MailChimpListForm(request.POST)
            if form.is_valid():
                form.save()
                messages.add_message(request, messages.INFO, "Mailing list configured!")
                return HttpResponseRedirect(reverse('admin-home'))

        
        form=MailChimpListForm()
        return render_to_response('admin/mailchimp_apikey.html', locals(), context_instance=RequestContext(request))
        return HttpResponse(lists)

@admin_required
def manage_users(request):
    site=get_site()
    users= site.profile_set
    if request.method == 'POST':
        updated_users=[]
        for key in request.POST.keys():
            #return HttpResponse(str(request.POST))
            if key.startswith('set-userlevel-'):
                
                u=site.profile_set.filter('slug = ', key[14:]).get()
                u.userlevel=int(request.POST[key])
                updated_users.append(u)
                
        db.put(updated_users)
    return render_to_response('admin/users.html', locals(), context_instance=RequestContext(request))
    
    



@admin_required
def logo(request):
    site=get_site()
    if request.method=='POST':
        files=get_uploads(request)
        for upload in files:
            if site.original_logo:site.original_logo.delete()
            site.original_logo=upload
            if site.original_logo_version:
                site.original_logo_version=site.original_logo_version+1
            else:
                site.original_logo_version=1
            ext=upload.filename.split('.')[-1]
            
            site.logo_asset_href=get_serving_url(str(upload.key()), 512)
            #site.logo_asset_href=reverse('original-logo',kwargs={'site_slug':site.slug,
            #                                            'version':site.original_logo_version,
            #                                            'ext':ext})
            
            
            
        site.put()
        site.expire_assets()
        return HttpResponseRedirect(reverse('logo-upload'))
    
    asset_href=site.logo_asset_href
    upload_url=blobstore.create_upload_url(reverse('logo-upload'))
    form=LogoUploadForm()
    return render_to_response('admin/logo.html', locals(), context_instance=RequestContext(request))
    
    
    
    
def migrate(request):
    
    def clone_entity(e, **extra_args):
      """Clones an entity, adding or overriding constructor attributes.

      The cloned entity will have exactly the same property values as the original
      entity, except where overridden. By default it will have no parent entity or
      key name, unless supplied.

      Args:
        e: The entity to clone
        extra_args: Keyword arguments to override from the cloned entity and pass
          to the constructor.
      Returns:
        A cloned, possibly modified, copy of entity e.
      """
      klass = e.__class__
      props = dict((k, v.__get__(e, klass)) for k, v in klass.properties().iteritems())
      props.update(extra_args)
      return klass(**props)
    
    
    
    set_namespace('')
    key_name = os.environ.get('HTTP_HOST')
    #site=site=models.Eventsite.all().filter('hostnames = ',key_name).get()
    site=Query(models.Eventsite, namespace='').filter('hostnames = ',key_name).get()
    if not site:return HttpResponse("Couldn't find a site to migrate")
    new_namespace=request.environ.get('HTTP_HOST').split(':')[0]
    old_chimp=site.chimp
    set_namespace(new_namespace)
    namespace_registry.register(new_namespace)
    new_site=clone_entity(site, key_name=new_namespace)
    new_site.put()
    namespace_registry.register(new_namespace)
    if old_chimp:
        new_chimp=clone_entity(old_chimp, parent=new_site)
        new_chimp.put()
    taskqueue.add(url='/admin/migrate-profiles/', params={'new_namespace':new_namespace,
                                        'old_site':site.key(),
                                        'new_site':new_site.key(),
                                        },)

    set_namespace('')                                                    
    return HttpResponse('Migrated Site')
    
    

templates/eventsite/admin.html
{% extends "base.html" %}

{% block content %}
<div class="row">
<form method="post">
{{ form.as_ul }}
<input type="submit" value="Submit">
</form>
</div>
{% endblock content %}

templates/eventsite/front-page.html
{% extends "base-cacheable.html" %}
{% load cdn_helper %}
{% load event_tags %}
{% load utility %}
{% load cache %}

{% load humanize %}

{% block headextra %}

{% if site.google_site_verification %}
<meta name="google-site-verification" content="{{site.google_site_verification}}" />
{% endif %}


{% endblock %}

{% block subtitle %}Front Page{% endblock %}


{% block content %}
<div id="positioner">
		
	<div class="row">
		<div class="cell position-0 width-10" id="events">
			
		
			<div id="thisweek">
			<!-- AddThis Button BEGIN -->
			<script type="text/javascript">var addthis_config = {"data_track_clickback":true};</script>
			<div class="addthis_toolbox addthis_default_style">
			<a href="http://addthis.com/bookmark.php?v=250&amp;username=rosskarchner" class="addthis_button_compact">Share</a>
			<span class="addthis_separator">|</span>
			<a class="addthis_button_facebook"></a>
			<a class="addthis_button_twitter"></a>
			</div>
			<script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#username=rosskarchner"></script>
			<!-- AddThis Button END -->
			
			{% for event in upcoming %}

			{% ifchanged event.local_start.date %}<h2>{{event.local_start.date|naturalday:"D n/j"  }}</h2> {% endifchanged %}
			{% include "events/one_event.html" %}

			{% endfor %}


			</div>


		
		</div>

		<div class="cell position-10 width-6" id="sidebar">
			
			{% include "eventsite/sidebar.html" %}
		
	</div>
	
	<div class="row">
		
		<div class="cell position-0 width-16" id="pagination">

			<form method="POST" action="/jumpto/" class="jumptoform" novalidate>
				<label>Select a day: </label><input type="date" name="jumptodate" value="" placeholder="{{site.today|date:'n/j/Y'}}" class="datepicker"/>
					<input type="submit" value="Go!">
				</form>


		</div>
	
	</div>
	

</div>
{% endblock %}


{% block endcode %}


{% endblock %}

templates/eventsite/front_page_this_week_header.html
<h1><a href="/week-of/{{ this_week_started|date:"Y-n-d" }}">This Week on {{site.name}}</a> <a name="thisweek"/></h1>

templates/eventsite/jump.html
<div> <form method="POST" action="{% url jumpto %}" novalidate>
	<label>Jump to a different day:</label> <input type="date" name="datestring" value="{{datestring}}"/>
	<input type="submit" value="Go!"/>
	</form>
</div>

templates/eventsite/newsletter.html
{% load humanize %}
{% load cdn_helper %}
<!doctype html>
<head><meta charset=utf-8>
<title>{{ site.name }} weekly newsletter for </title>

<style>
body {
	font: small "Helvetica Neue", Arial, Helvetica, Geneva, sans-serif;
}

h1{
	font-size: medium;
}

a{
	text-decoration: none;
	color:blue;
}

table{
	
	margin-top:10px;
}

div{margin:10px;}

</style>


</head>
<body>
	
		
			{% if site.logo_asset_href %}
			<img src="{{site.logo_asset_href }}" alt="{{ site.name }}">
			{% else %}
			{{ site.name }}
			{% endif %}
			
			
<h1> <a href="http://{{site.host}}{% url front-page %}">{{ site.name }} for the week of {{ start|date:"F j, Y"}}</a></h1>

	<div id="tagline"><strong>{{site.name}}</strong> is a calendar for {{site.audience}}</div>


			<div>Please consider forwarding this along to your friends and colleagues in the community. If you find it useful, they might too.</div>
		
				<div>Did we miss something? <a href="http://{{site.host}}/events/add">You can still add events</a>!</div>
				<div>
				
			<table>
			{% for event in continuing %}
			    <tr>
				{% ifequal forloop.counter 1 %}
				<td>Continuing</td>
				{% else %}
				<td>&nbsp;</td>
				
				{% endifequal %}
			{% include "events/one_event_newsletter.html" %}</tr>
				{% if forloop.last %}
				
				{% endif %}
		
			{% endfor %}

			{% for event in events_soon %}
			<tr>
            {% ifchanged event.local_start.date %}    
				<td>{{event.local_start.date|date:"D"  }}</td> 
            {% else %}
				<td>&nbsp;</td>
			{% endifchanged %}
		    {% include "events/one_event_newsletter.html" %}
			
			</tr>
			{% endfor %}	
			
			</table>
	</div>
<div>Thank you so much for reading!</div>
	

</div>

templates/eventsite/sidebar.html
	<div>
{% if site.bsa_code %}

{{ site.bsa_code|safe }}

{% else %}
<script type="text/javascript"><!--
google_ad_client = "ca-pub-8225997618118622";
/* Bigger Better */
google_ad_slot = "4188848263";
google_ad_width = 250;
google_ad_height = 250;
//-->
</script>
<script type="text/javascript"
src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
{% endif %}
</div>

	<div>
	
			
		<h2>Subscribe to {{site.name}}</h2>
		<form method="post" action="/subscriptions/new/">
		<input id="id_email" type="text" name="email" maxlength="255" placeholder="you@whatever.com">
		<input type="Submit" value="Subscribe"/>
		</form>
	
	</div>
	<div id="ical">Or, get the <a href="webcal://{{site.host}}/ical">iCal</a>
	or <a href="/thisweek.xml">RSS feed</a>
	</div>




	{% if links %}
	<div>
	
	<h2>Community Links</h2>
	<ul id="links">
	{% for link in links %}
	<li><a href="{{link.href}}">{{link.name}}</a></li>
	{% endfor %}
	(<a href="/links/add" id="addlink">Submit a link</a>)
	</div>
	{% endif %}
	
</div>

templates/eventsite/tagpage.html
{% extends "base.html" %}
{% load cdn_helper %}
{% load humanize %}

{% block headextra %}
{% ifequal user.userlevel 10 %}
	<script src="{% versioned "/static/editing.js" %}"></script>
{% endifequal %}
{% endblock %}
{% block subtitle %} {{tag}} events{% endblock %}

{% block opengraph %}
<meta name="title" content="events tagged {{tag}} on{{ site.name }}" />
<meta name="description" content="{{site.name}} is a calendar for {{site.audience}} " />
<meta property="og:type" content="article" />
{% endblock opengraph %}


{% block content %}
<div id="positioner">
	
	<div class="row">
		<div class="cell position-0 width-12" id="events">
			<a href="/">return to front page</a>
		<h1> upcoming events tagged <em>{{ tag }}</em></h1>
		<div id="utilities">
			
				<div id="tagsubscribe">subscribe to this tag with <a href="webcal://{{site.host}}/tag/{{tag}}/ical">ical</a></div>
			
				<!-- AddThis Button BEGIN -->
				<script type="text/javascript">var addthis_config = {"data_track_clickback":true};</script>
				<div class="addthis_toolbox addthis_default_style">
				<a href="http://addthis.com/bookmark.php?v=250&amp;username=rosskarchner" class="addthis_button_compact">Share</a>
				<span class="addthis_separator">|</span>
				<a class="addthis_button_facebook"></a>
				<a class="addthis_button_twitter"></a>
				</div>
				<script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#username=rosskarchner"></script>
				<!-- AddThis Button END -->
	
		</div>
			{% for event in continuing %}
			 
				{% ifequal forloop.counter 1 %}
				<h2>Continuing</h2>
				{% endifequal %}
			{% include "events/one_event.html" %}
			{% ifequal user.userlevel 10 %}
			{% include "events/edit_form.html" %}
			{% endifequal %}
		
			{% endfor %}

			{% for event in more_events %}
			
            {% ifchanged event.local_start.date %}    
				<h2>{{event.local_start.date|naturalday  }}</h2> 
            
			{% endifchanged %}
		    {% include "events/one_event.html" %}
			{% ifequal user.userlevel 10 %}
			{% include "events/edit_form.html" %}
			{% endifequal %}
		
			{% endfor %}	


	</div>
		<div class="cell position-12 width-4" id="sidebar">
			
			{% include "eventsite/sidebar.html" %}
			
		</div>
	
</div>
	

</div>
{% endblock %}

templates/eventsite/week.html
{% extends "base.html" %}
{% load cdn_helper %}
{% load humanize %}
{% load utility %}

{% block headextra %}
{% ifequal user.userlevel 10 %}
	<script src="{% versioned "/static/editing.js" %}"></script>
{% endifequal %}
{% endblock %}
{% block subtitle %}Week of {{ start|date:"F j, Y"}}{% endblock %}


{% block opengraph %}
<meta name="title" content="{{ site.name }} for the week of {{ start|date:"F j, Y"}}" />
<meta name="description" content="{{site.name}} is a calendar for {{site.audience}} " />
<meta property="og:type" content="article" />
{% endblock opengraph %}


{% block content %}
<div id="positioner">
	
	
	<div class="row">
		<div class="cell position-0 width-12" id="events">
			<h1> upcoming events for the week of <em>{{ start|date:"F j, Y"}}</em></h1>
				<div>
					<!-- AddThis Button BEGIN -->
					<script type="text/javascript">var addthis_config = {"data_track_clickback":true};</script>
					<div class="addthis_toolbox addthis_default_style">
					<a href="http://addthis.com/bookmark.php?v=250&amp;username=rosskarchner" class="addthis_button_compact">Share</a>
					<span class="addthis_separator">|</span>
					<a class="addthis_button_facebook"></a>
					<a class="addthis_button_twitter"></a>
					</div>
					<script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#username=rosskarchner"></script>
					<!-- AddThis Button END -->
				
				</div>
			{% for event in continuing %}
			 
				{% ifequal forloop.counter 1 %}
				<h2>Continuing</h2>
				{% endifequal %}
			{% include "events/one_event.html" %}
			{% ifequal user.userlevel 10 %}
			{% include "events/edit_form.html" %}
			{% endifequal %}
		
			{% endfor %}

			{% for event in events_soon %}
			
            {% ifchanged event.local_start.date %}    
				<a name="{{event.local_start.date|date:'Y-m-d' }}">
				<h2>{{event.local_start.date|naturalday  }}</h2> 
            
			{% endifchanged %}
		    {% include "events/one_event.html" %}
			{% ifequal user.userlevel 10 %}
			{% include "events/edit_form.html" %}
			{% endifequal %}
		
			{% endfor %}	
			
			

	
	</div>
	<div class="cell position-12 width-4" id="sidebar">
		
		{% include "eventsite/sidebar.html" %}
		
	</div>

	

</div>
{% endblock %}

{% block endcode %}
<script type="text/javascript">
var disqus_shortname = '{{site.disqus_shortname}}';
(function () {
  var s = document.createElement('script'); s.async = true;
  s.src = 'http://disqus.com/forums/{{site.disqus_shortname}}/count.js';
  (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
}());
</script>


{% endblock %}